spring:
  profiles:
      active: dev
management:
  security:
    enabled: false
security:
  basic:
    enabled: false

---

# Dev profile
spring:
  datasource:
    url: jdbc:h2:~/test
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jooq:
    sql-dialect: h2
  profiles: dev
logging:
  level:
    org.springframework.web: debug
    com.jooq: debug

---

# Prod profile
spring:
  datasource:
    url: jdbc:h2:~/test
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jooq:
    sql-dialect: h2
  profiles: prod
